FROM python:3.8.6-slim-buster

ARG AZURE_STORAGE_KEY_ARG=abcd
ARG ENDPOINT_SUFFIX_ARG=abcd
ARG AZURE_STORAGE_ACCOUNT_ARG=abcd
ARG PORT_ARG=3080

WORKDIR /app

COPY ./app /app
# RUN ls -la /app/*

RUN pip install -r requirements.txt
# RUN pip freeze

ENV AZURE_STORAGE_KEY=$AZURE_STORAGE_KEY_ARG \
    ENDPOINT_SUFFIX=$ENDPOINT_SUFFIX_ARG \
    AZURE_STORAGE_ACCOUNT=$AZURE_STORAGE_ACCOUNT_ARG \
    PORT=$PORT_ARG

EXPOSE $PORT

RUN python3 app_download_data.py

ENTRYPOINT [ "python3", "-m" ]
CMD ["panel", "serve", "--port=5006", "--allow-websocket-origin=localhost:8000", "panel_file2.py", "--dev"]
