FROM python:3.8.6-slim-buster

ARG AZURE_STORAGE_KEY_ARG=abcd
ARG ENDPOINT_SUFFIX_ARG=abcd
ARG AZURE_STORAGE_ACCOUNT_ARG=abcd
ARG PORT_ARG=3080
ARG PY_VERSION=3.8

WORKDIR /app

COPY ./app /app
# RUN ls -la /app/*

RUN python -m pip install --upgrade pip \
    && pip install -r requirements.txt \
    && find /usr/local/lib/python$PY_VERSION -name '*.c' -delete \
    && find /usr/local/lib/python$PY_VERSION -name '*.pxd' -delete \
    && find /usr/local/lib/python$PY_VERSION -name '*.pyd' -delete \
    && find /usr/local/lib/python$PY_VERSION -name '__pycache__' | xargs rm -r
# RUN pip freeze

ENV AZURE_STORAGE_KEY=$AZURE_STORAGE_KEY_ARG \
    ENDPOINT_SUFFIX=$ENDPOINT_SUFFIX_ARG \
    AZURE_STORAGE_ACCOUNT=$AZURE_STORAGE_ACCOUNT_ARG \
    PORT=$PORT_ARG

EXPOSE $PORT

RUN python3 app_download_data.py

ENTRYPOINT [ "python3", "-m" ]
CMD ["panel", "serve", "--port=5006", "--allow-websocket-origin=localhost:8000", "panel_file2.py", "--dev"]
